# Generated by Django 5.2.4 on 2025-07-28 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_complaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(blank=True, max_length=15)),
                ('expected_datetime', models.DateTimeField()),
                ('status', models.CharField(choices=[('EXPECTED', 'Expected'), ('ARRIVED', 'Arrived'), ('DEPARTED', 'Departed')], default='EXPECTED', max_length=20)),
                ('arrival_time', models.DateTimeField(blank=True, null=True)),
                ('departure_time', models.DateTimeField(blank=True, null=True)),
                ('visiting_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-expected_datetime'],
            },
        ),
    ]
