# Generated by Django 5.2.4 on 2025-08-02 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_user_date_of_birth_user_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='society',
            name='notice_image',
            field=models.ImageField(blank=True, default='noticeboard_images/notice.jpg', null=True, upload_to='noticeboard_images/'),
        ),
    ]
