# Generated by Django 5.2.4 on 2025-08-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_society_notice_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='society',
            name='notice_image',
        ),
        migrations.AddField(
            model_name='notice',
            name='notice_image',
            field=models.ImageField(blank=True, default='noticeboard_images/notice.jpg', null=True, upload_to='noticeboard_images/'),
        ),
    ]
